import CardsShuffleBlock from "@/components/CardsShuffleBlock";
import FullScreenText from "@/components/FullScreenText";
import Header from "@/components/Header";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <CardsShuffleBlock />
        <FullScreenText
          text={
            "We love to visualize stories because we love people and they inspire us."
          }
        />
      </main>
    </>
  );
}
